#服务器端口

server:
  port: 8081
  max-http-header-size: 102400
  tomcat:
    max-http-form-post-size: 10MB
#datasourceas
spring:
  datasource:
    username: root
    password: 2364555434
    data-username: root
    data-password: 2364555434
    url: jdbc:mysql://1.117.229.165:3306/myblog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: myblog
  mvc:
    static-path-pattern: /static/**
  hikari:
    minimum-idle: 5
    maximum-pool-size: 20
    auto-commit: true
    connection-timeout: 30000
    pool-name: hikariCP
    max-lifetime: 30000
    idle-timeout: 30000
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    servlet:
      content-type: text/html
      ##redisson配置

  redis:
    redisson:
      config:
        classpath: redisson.yml
    host: 1.117.229.165
    port: 6379
    password: 2364555434
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
    timeout: 0
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB


#mybatisConfig
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    call-setters-on-nulls: false
    map-underscore-to-camel-case: false
#虚拟路径设置
#fastDFS设置
fdfs:
  so-timeout: 6000

  connect-timeout: 6000
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 1.117.229.165:22122
  pool:
    #从池中借出的对象的最大数目（配置为-1表示不限制）
    max-total: -1
    #获取连接时的最大等待毫秒数(默认配置为5秒)
    max-wait-millis: 5000
    #每个key最大连接数
    max-total-per-key: 50
    #每个key对应的连接池最大空闲连接数
    max-idle-per-key: 10
    #每个key对应的连接池最小空闲连接数
    min-idle-per-key: 5
#  日志指定位置生成
logging:
  file:
    name: springboot.log




